# CircleCI configuration file
version: 2.1

commands:
  restore_gem_cache:
    description: Restore ruby dependencies cache
    steps:
      - restore_cache:
          keys:
          - v1-gem-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-gem

  install_bundler:
    description: Ensure bundler is installed
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")

  install_dependencies:
    description: Install ruby dependencies with bundler
    steps:
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle

  save_gem_cache:
    description: Save ruby dependencies cache
    steps:
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-gem-{{ checksum "Gemfile.lock" }}

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.3
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - restore_gem_cache
      - install_bundler
      - install_dependencies
      - save_gem_cache
      # build
      - run:
          name: Run build task
          command: bundle exec jekyll build
      # test
      - run:
          name: Run test task
          command: bundle exec htmlproofer ./_site  --check-html --allow-hash-href --empty-alt-ignore --only-4xx
      - persist_to_workspace:
          root: .
          paths:
            - _site
            - .circleci

  deploy-gh-pages:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b9:b3:45:cf:b9:14:45:5f:6f:da:2c:2c:f5:a6:2c:43"
      - checkout:
          path: /tmp/gh-pages
      - attach_workspace:
          at: .
      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "no-reply@agid.gov.it"
            git config --global user.name "AGID deploy"
            
            cd /tmp/gh-pages
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .

            cp -a ~/project/_site/. .
            echo "peppol.agid.gov.it" > CNAME
            # copy .circleci as well so that the branch filter is honored
            mkdir -p .circleci && cp -a ~/project/.circleci/. .circleci/.

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: gh-pages

      - deploy-gh-pages:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
